# Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Type I and Type II errors

4) Chi-Squared Tests

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm on a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [0]:
from scipy import stats 
import numpy as np

In [2]:
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

**First T test**

*One sample t-test*

Check if the mean of the GPU1 is equal to zero.
- Null Hypothesis is that mean is equal to zero.
- Alternate hypothesis is that it is not equal to zero.

In [39]:
import numpy as np
from scipy import stats 
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

GPU1_Mean =  GPU1.mean() # OR     GPU1_Mean = np.mean(GPU1)
print("GPU1 Mean is :",GPU1_Mean)
print("Reject Null Hypothesis.")

# H0 = 0 & HA ≠ 0
# Here Mean is 10.33 
# So the statistical decision is to reject the null hypothesis.

GPU1 Mean is : 10.333333333333334
Reject Null Hypothesis.


## Question 2

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [50]:
import numpy as np
from scipy import stats 
import scipy.stats
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])
Test = scipy.stats.ttest_ind(GPU1, GPU2, axis=0, equal_var=True, nan_policy='propagate')
print (Test)
print("Reject Null Hypothesis as P<5%.")

Ttest_indResult(statistic=-2.627629513471839, pvalue=0.013794282041452725)
Reject Null Hypothesis as P<5%.


## Question 3

He is trying a third GPU - GPU3.

In [0]:
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])

#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed.

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

#### Answer:

In [85]:
import numpy as np
from scipy import stats 
import scipy.stats

GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])

#Null Hypothesis : There is no significant difference between data sets.
#Alternate Hypothesis : There is a significant difference.

t_statistic, p_value_GPU1_GPU3  =  stats.ttest_ind(GPU1,GPU3)
print('P Value of GPU1 & GPU3 : %1.3f' % p_value_GPU1_GPU3)

print("In this example, p value is 0.145 and it is more than 5% level of significance.")
print("So the statistical decision is to accept the null hypothesis at 5% level of significance.")

P Value of GPU1 & GPU3 : 0.145
In this example, p value is 0.145 and it is more than 5% level of significance.
So the statistical decision is to accept the null hypothesis at 5% level of significance.


## ANOVA

## Question 4 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [0]:
import numpy as np

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed

Perform levene test on the data

The Levene test tests the null hypothesis that all input samples are from populations with equal variances. Levene’s test is an alternative to Bartlett’s test bartlett in the case where there are significant deviations from normality.

source: scipy.org

#### Answer:

In [11]:
import numpy as np
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#print('Count, Mean and standard deviation of e1: %3d, %3.2f and %3.2f' % (len(e1), e1.mean(),np.std(e1,ddof =1)))
#print('Count, Mean and standard deviation of e2: %3d, %3.2f and %3.2f' % (len(e2), e2.mean(),np.std(e2,ddof =1)))
#print('Count, Mean and standard deviation of e3: %3d, %3.2f and %3.2f' % (len(e3), e3.mean(),np.std(e3,ddof =1)))
print(stats.levene(e1,e2,e3))
print("As P value>5%, it means the variances of e1,e2 & e3 are approximately equal.")
print("So the statistical decision is to retain the null hypothesis at 5% level of significance.")

LeveneResult(statistic=2.6741725711150446, pvalue=0.12259792666001798)
As P value>5%, it means the variances of e1,e2 & e3 are approximately equal.
So the statistical decision is to retain the null hypothesis at 5% level of significance.


## Question 5

The one-way ANOVA tests the null hypothesis that two or more groups have the same population mean. The test is applied to samples from two or more groups, possibly with differing sizes.

use stats.f_oneway() module to perform one-way ANOVA test

In [13]:
print("scipy.stats.f_oneway(sample1, sample2, ....)")

scipy.stats.f_oneway(sample1, sample2, ....)


## Question 6

*In one or two sentences explain about **TypeI** and **TypeII** errors.*

#### Answer:

1) Type 1 Error is rejecting the null hypothesis when H0 is actually true.
2) Type 2 Error is failing to reject the null hypothesis when the alternative is actually true.

## Question 7 

You are a manager of a chinese restaurant. You want to determine whether the waiting time to place an order has changed in the past month from its previous population mean value of 4.5 minutes. 
State the null and alternative hypothesis.

#### Answer:


Null Hypothesis      : Mean value of waiting time to place an order has not changed in the past month from its previous population. So both mean are equal.  


Alternate hypothesis : Mean value of waiting time to place an order has changed in the past month from its previous population. So both mean are not equal.

## Chi square test

## Question 8

Let's create a small dataset for dice rolls of four players

In [0]:
import numpy as np

d1 = [5, 8, 3, 8]
d2 = [9, 6, 8, 5]
d3 = [8, 12, 7, 2]
d4 = [4, 16, 7, 3]
d5 = [3, 9, 6, 5]
d6 = [7, 2, 5, 7]

dice = np.array([d1, d2, d3, d4, d5, d6])

run the test using SciPy Stats library

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold.

For our purposes, we’ll use 0.01 as the threshold.

use stats.chi2_contingency() module 

This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed frequencies in the contingency table

Print the following:

- chi2 stat
- p-value
- degree of freedom
- contingency



In [1]:
import numpy as np
import scipy
from scipy import stats
from scipy.stats import chi2

d1 = [5, 8, 3, 8]
d2 = [9, 6, 8, 5]
d3 = [8, 12, 7, 2]
d4 = [4, 16, 7, 3]
d5 = [3, 9, 6, 5]
d6 = [7, 2, 5, 7]

dice = np.array([d1, d2, d3, d4, d5, d6])

print("chi2 stat, p-value,degree of freedom & contingency are :\n", scipy.stats.chi2_contingency(dice, correction=True, lambda_=None))
print("As pvalue>0.01, we can not reject the null hypothesis")

chi2 stat, p-value,degree of freedom & contingency are :
 (23.315671914716496, 0.07766367301496693, 15, array([[ 5.57419355,  8.20645161,  5.57419355,  4.64516129],
       [ 6.50322581,  9.57419355,  6.50322581,  5.41935484],
       [ 6.73548387,  9.91612903,  6.73548387,  5.61290323],
       [ 6.96774194, 10.25806452,  6.96774194,  5.80645161],
       [ 5.34193548,  7.86451613,  5.34193548,  4.4516129 ],
       [ 4.87741935,  7.18064516,  4.87741935,  4.06451613]]))
As pvalue>0.01, we can not reject the null hypothesis


## Question 9

### Z-test

Get zscore on the above dice data using stats.zscore module from scipy. Convert zscore values to p-value and take mean of the array.

In [10]:
z_score=scipy.stats.zscore(dice, axis=0, ddof=0)
pvalue=scipy.stats.norm.sf(abs(z_score))
mean=np.mean(pvalue)
print("Z score:\n",z_score)
print("pvalue:\n",pvalue)
print("mean :\n",mean)

Z score:
 [[-0.46291005 -0.18884739 -1.83711731  1.44115338]
 [ 1.38873015 -0.64208114  1.22474487  0.        ]
 [ 0.9258201   0.7176201   0.61237244 -1.44115338]
 [-0.9258201   1.62408759  0.61237244 -0.96076892]
 [-1.38873015  0.03776948  0.          0.        ]
 [ 0.46291005 -1.54854863 -0.61237244  0.96076892]]
pvalue:
 [[0.32171442 0.42510621 0.03309629 0.07477068]
 [0.08245741 0.26041025 0.11033568 0.5       ]
 [0.17726974 0.23649578 0.27014569 0.07477068]
 [0.17726974 0.05217856 0.27014569 0.16833418]
 [0.08245741 0.48493574 0.5        0.5       ]
 [0.32171442 0.06074513 0.27014569 0.16833418]]
mean :
 0.23428473233691496


## Question 10

A Paired sample t-test compares means from the same group at different times.

The basic two sample t-test is designed for testing differences between independent groups. 
In some cases, you might be interested in testing differences between samples of the same group at different points in time. 
We can conduct a paired t-test using the scipy function stats.ttest_rel(). 

In [0]:
before= stats.norm.rvs(scale=30, loc=100, size=500) ## Creates a normal distribution with a mean value of 100 and std of 30
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Test whether a weight-loss drug works by checking the weights of the same group patients before and after treatment using above data.

In [64]:
import numpy as np
import scipy
from scipy import stats

before = stats.norm.rvs(scale=30, loc=100, size=500)
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Statistics_pvalue = stats.ttest_rel(before, after)
print(Statistics_pvalue)


Ttest_relResult(statistic=4.302298994077453, pvalue=2.0346395248327802e-05)
